#Oversikt over fagett
- Tre hovedtemaer: 
    1. Konjunktursvingninger
    1. Økonomisk vekst
    1. Økonomiske kriser

- Tilknyttet dette ønsker vi å undersøke
    + Hva forårsaker konjunktursvingninger, økonomiske vekst og økonomiske kriser
    + Hvilken rolle bør offentlige myndigheter spille
    
- Sentral økonomer i makroøkonomi som har gitt vesentlige bidrag til å besvare disse spørsmålene:
    + Keynes (1883-1946) / Krugman(1953-)
    + Friedman (1912-2006)
    + Minsky (1919-1996)
    + Hayek (1899-1992) 
    
- Aktørene i økonomien:
    + Husholdninger 
    + Bedrifter 
    + Finansinstitusjoner 
    + Sentralbanken 
    + Offentlige myndigheter

- Markedene: 
    + Vare- og tjenestemarkedet
    + Pengemarkedet 
    + Arbeidsmarkedet
    + Finansinstitusjoner (investering- og forretningsbanker) 
    + Valutakursmarkedet.

- To typer økonomier:
    + Lukket (eller globalisert) økonomi
    + Åpen økonomi
    
#Del 1
##Grunnleggende bakgrunnskunnskap
- Bruttonasjonalprodukt (GDP/BNP)

- Bruttonasjonalinntekt (GNP/BNI)

- Nominell BNP ($LY$)
$$LY = PY$$
- Reel BNP
$$Y = \frac{LY}{P}$$

- Arbeidsledighetsrate:

$$u = 1-\frac{L}{N}$$

- Inflasjon 

$$\pi = \frac{\Delta P}{P} =\frac{P_{t} - P_{t-1}}{P_{t-1}}$$

- Okuns lov:
negativ korrelasjon mellom endring i arbeidsledighet og vekst BNP 

- Phillips-kurven:
negativ sammenheng mellom arbeidsledighet og endring i inflasjon

- Hvordan bestemmes BNP?
    + Kort sikt
    + Mellomlang sikt
    + Lang sikt

## Lukket økonomi
Aggregert etterspørsel (AE) i en lukket økonomi    

$AE \equiv C + I + G$

### Likevekt i godemarkedet (varer og tjenester)

Hvor vi postulerer følgene adferdlikginger

- Husholdningene:
$$C = \overline{C} + c(Y-T)$$
- Bedriftene:
$$I = \overline{I} - b\cdot i$$

- Sentralbanken
$$i = \overline{i}$$

- Offentlige myndigheter
$$G = \overline{G}$$  
$$T = t\cdot Y$$ 

Løser denne modellen mhp. på Y gir oss IS-likningen (kombinasjoner av i og Y som er forenlig med likevekt i varemarkedet)

$$Y = \frac{1}{1-c}  \left [ \overline{C} -c\cdot \overline{T} - b\cdot \overline{i} + \overline{G}  \right ]$$

Skiftanalyse (matematisk, figur, og verbalt): Eks. endring i $\Delta Y$ som følge av en økning i $\Delta \overline{I}$:

- Matematisk:

$$\Delta Y = \frac{1}{1-c}\Delta  \overline{I}>0 \text{ eller } \frac{\Delta Y}{\Delta  \overline{I} } = \frac{1}{1-c}>1$$

- Figur: (se notater)

- Verbalt  (dynamisk forklaring utenfor modellen):
Økte investeringer $\rightarrow$ økt produksjon $\rightarrow$ initierer en multiplikatoreffekt: $\rightarrow$ økt disponibel inntekt $\rightarrow$ økt konsum $\rightarrow$ økt produksjon osv.

Stabiliseringspolitikk: $\Delta G <0$

$$\Delta Y = \frac{1}{1-c}  \left [ \Delta \overline{I} + \Delta \overline{G} \right ]$$

Dersom vi lar $\Delta \overline{I} = - \Delta \overline{G} > 0 \Rightarrow \Delta Y = 0$ (dvs. intern balanse)

### Likevekt i pengemarkedet 
- Tilbudet av penger ($M^{s}$)

Ser foreløpig kun på utvendige penger: Sedler og mynt pluss reserver. Dette nivået blir bestemt av sentralbanken
$\overline{M}/P$

- Etterspørsel etter penger:
$$L_{d} = \kappa Y -hi$$

- Likevekt i pengemarkedet: 
$$M/P = L_{d}$$  

Sentralbanken bestemmer hva som skjer i pengemarkedet ved
(1) Endre tilbudet av penger (vanlig tidligere) eller (2) å endre rentenivået (vanlig i dag).

## IS-LM modellen for en lukket økonomi: Gode- og pengemarkedet i likevekt

- Varemarkedet

$$Y = \frac{1}{1-c(1-t)}  \left [ \overline{C} -c\cdot \overline{T} - b\cdot \overline{i} + \overline{G}  \right ]$$
$\Rightarrow$ IS-kurven

$$\Delta Y =\left[\frac{-b}{1-c(1-t)}\right ]   \cdot \Delta \overline{i}<0$$
- Pengemarkedet
$$kY -hi = \overline{M}/P$$
$\Rightarrow$ LM-kurven

$$\Delta Y =\left[\frac{-b}{1-c(1-t)}\right ]   \cdot \Delta \overline{i}<0$$

- Grafisk tegning bestemmer her $i$ og $Y$ samtidig

- Skiftanalyse (grafisk og verbalt)
Merk: P gir AD-kurven

- Stabiliseringspolitikk (grafisk og verbalt)
Virkemidler: $G, T, M/i$

### AD-AS modellen for en lukket økonomi: Gode, penge og arbeidsmarkedet i likevekt

- Husholdningene: Tilbyr arbeid

$$W=P^{e}F(\underset{(-)}{u}, \underset{(+)}{z})$$

- Bedrifter: Etterspør arbeidskraft og tilbyr produktet i et marked med monopolistisk konkurranse

$$Y=AL$$

$$P=(1+μ)W$$

- Ledighet

$$u=\frac{U}{N}=\frac{N-L}{N}=1−\frac{L}{N}=1−\frac{Y/A}{N}=1 - \frac{Y}{AN}$$

- Kombinere dett gir oss AS-kurven (verdier av P og Y som gir likevekt i arbeidsmarkedet)

$$P=(1+μ)P^{e}F(1 - \frac{Y}{AN},z)$$

- AD-AS-modellen

$$Y = \frac{1}{1-c}  \left [ \overline{C} -c\cdot \overline{T} - b\cdot \overline{i} + \overline{G}  \right ]\text{ :Godemarkedet}$$ 

$$\frac{\overline{M}}{P}=\kappa Y - h\cdot i  \text{ :Pengemarkedet}$$

$$P=(1+μ)PeF(1−YAL,z) \text{ :Arbeidsmarkedet}$$ 

Merk: $P=Pe⇒Y=Yn=u=un$: Naturlige produksjons- og ledighetsnivået,

Grafisk tegning bestemmer her P, Y
og i samtidig

- Skiftanalyse (grafisk og verbalt)
- Stabiliseringspolitikk (grafisk og verbalt)

Virkemidler: $G$, $T$ og $M/i$

- Sentral poeng med modellen – Selvkorrigerende mekanismer:

Fleksibilitet i P og korrekte prisforventninger Pe
 på mellomlang sikt, fører til at økonomien går tilbake til sitt naturlige produksjons- og ledighetsnivå.

<!--

### IS-LM modellen for en åpen økonomi: Gode-, penge- og valutakursmarkedet i likevekt

- Tre fundamentale endringer fra en lukket økonomi:

1. Handel med utlandet

1. Internasjonale finansmarkeder

1. Fast eller flytende kurs

$$AE = C+I+G+NX$$

$$ NX=EX−R∗IM    $$

$$ BP = CA + CP + OR=0 $$

CU=Driftsregnskapet: Nettoeksport, Nettofinansinntekter(aksjer og obligasjoner), Nettoverføringer

CA=Kapitalregnskapet: Nettoendringer i fordringer og gjeld ovenfor utlandet

- To stabiliseringsmål:

1. Intern balanse (produksjon lik naturlig produksjonsnivå)

1. Ekstern balanse (rimelig nivå på utenlandsgjelden)

- Handel med utlandet (avhenger blant annet av relative prisnivået mellom innenlandske og utenlandske varer)

Realvalutakursen: $R=\frac{EP}{P}$

- E: Pris (nominell) per enhet av utenlandsk (innenlandsk) valuta E  (1/E)

- Postulerer følgende adferdsligninger for handelsbalansen

$$IM=X(\underset{(-)}{R}, \underset{(+)}{Y}) =  -m_{1}R + x_{2}Y $$
$$EX=X(\underset{(+)}{R}, \underset{(+)}{Y^{*}}) = x_{1}R + x_{2}Y^{*}  $$

Det betyr at

- $$NX = EX - IM = x_{1}R + x_{2}Y^{*} + m_{1}R - x_{2}Y$$

Legger til grunn i dette kurset at $\frac{\Delta NX}{\Delta R}/>0$  (i praksis kan dette ta litt tid)

- internasjonale finansmarkeder (renteparitetsbetingelsen)

$$(1+i_{t+1})=(1+i_{t+1}^{*})\frac{E_{t+1}^{e}}{E_{t}}$$

- Myndighetene kan velge fast eller flytende kurs

Flytende: 

$E=\frac{(1+i)}{(1+i)}E^{e}$ 

Fast (troverdig $⇒E=E_{e}$): 

$i =i^{*}$

- Modellen
1. $$Y = \frac{1}{1-c-R?}  \left [ \overline{C} -c\cdot \overline{T} - b\cdot \overline{i} + \overline{G}  \right ]$$
1. $$\frac{M}{P}=\kappa\cdot Y + h\cdot i$$
1. $$E = \frac{1+i^{*}}{1 + i} \text{ Flytende kursregime}$$
1. $$i = i^{*} \text{ Fastkursregime}$$

- IS-kurven under fast og flytende kurs

Generelt fører lavere rente til høyere produksjon.

Men multiplikatoren blir mindre ved en åpen økonomi, grunnet importlekkasje.

Helningen på kurven er slakere under flytende kurs enn med fast kurs. Det skyldes at lavere rente under flytende kurs fører til en depresiering av den nominelle og realvalutakursen, noe som forbedrer landets konkurranse evne og dermed fører til økt etterspørsel gjennom økt nettoeksport.

- LM modellen stigende under fast og horisontal under fast(?)

- Skiftanalyse (grafisk og verbalt)

Merk: P gir AS-kurven.

- Stabiliseringspolitikk (grafisk og verbalt)

Virkemidler: $G$, $T$ og $M/i$
 (Flytende) og
$G$,$T$ og($E$)
 (Fast kurs)
 

### Mundell-Fleming (IS-LM for en åpne økonomi) modellen 

- AS-kurven samme som under en lukket økonomi.
- AD-kurven er fallende ved at økt priser fører til lavere etterspørsel.
- Sentralt poeng med modellen – Selvkorrigerende mekanismer:

Fleksibilitet i P og korrekte prisforventninger Pe
på sikt, fører til at økonomien på sikt går tilbake til sin naturlige produksjons- og ledighetsnivå.

# Del 2: Økonomisk vekst

## Introduksjon økonomisk vekst

-
YL↑⇒Høyere levestendard ⇒Lykke(?)
- Empiriske observasjoner:

Rike land: Har vokst og BNP per innbygger har konvergert.

Fattige land: Ingen slik klar sammenheng.

- Forklaringer:

Institusjoner, korrupsjon, sterk befolkningsvekst etc.

## Solow model for økonomisk vekst

- Hvordan forstå vekst?  Benytte Solow-modellen som består av tre komponenter:

- (1) Produktfunksjonen

$$Y=F(K,AL) \text{ } F^{'}_{K}>0, F^{''}_{KK}<0, F^{'}_{L}>0, F^{''}_{LL}<0$$

Konstant skalautbytte $\Rightarrow$

$$y=f(k) \text{  } f^{'}_{k}>0, f{''}_{k}>0 \text{ (produktfunksjonen på intensiv form)}$$ 

- (2) Sparing

Lukket økonomi (og uten offentlig sektor)

$$I=S$$

$$I=S=sY \Leftrightarrow \frac{I}{L} = \frac{sY}{L} f(k)$$
 
- (3) Kapitalakkumulasjon

**Enkel utgave (uten teknologisk framgang og befolkningsvekst):**

$$\Delta K=−\delta K+I$$

$$ \frac{\Delta K}{L} = \frac{\delta K}{L} + \frac{}{L}  $$

$$ \Delta k = sf(k)−\delta\cdot k $$

**Vanlig utgave (med teknologisk framgang, $a$, og befolkningsvekst, $n$,)**:

$$ \Delta k = sf(k)− (\delta +n + a)k $$

- Modellens prediksjon (bør også kunne vises grafisk):

Uavhengig av det initiale kapitalnivået, vil økonomien på sikt konvergere mot en steady state:

$$sf(kss)=(δ+n+a)kss$$

$$yss=f(kss)$$

I den enkle versjonen vil veksten i produksjonen (BNP) våre lik null.

I den vanlige versjonen vil veksten i produksjonen (BNP) våre lik befolkningsveksten pluss teknologiveksten.

Dette tilsvarer trendlinjen eller potensielle produksjonen, som vi snakket om i Del 1 av dette kurset

- Skiftanalyse (bør også kunne vises grafisk)

Økt sparing vil gi en ny og høyere steady state.

Befolkningsvekst (fødselsrater + nettoinnvandring)) vil gi en ny og lavere steady state.

# Del 3: Økonomiske kriser

## Tema 1: Penger, kreditt og bankadferd

## Pengens funksjoner

- Penger som gjeld

Utvendige penger (M0(M1)):

Skapt av sentralbanken og består av sedler, mynt pluss forretningsbankenes innskuddskontoer i sentralbanken.

Innvendige penger(M1(M2)-M0(M1)) :

Skapt av bankene ved at de krediterer sine innskuddskontoer.

## Tre arketyper for banksystemets forskjellige utforminger

- System 1: Lånebasert økonomi

Problemer:

Uelastisk kredittilbud.

Kostnader ved å flytte reserver mellom forretningsbankene.

- System 2: Fraksjonsbasert bankvirksomhet uten sentralbank

Problemer:

Åpne for løp på bankene.

Kostnader ved å flytte reserver mellom forretningsbankene.

- System 3: Fraksjonsbasert bankvirksomhet med sentralbank og fiat penger

Problemer:

Systemrisiko.

Vilkårlig omfordeling av formue.

## Banker og systemrisiko

- Bloos rule: Innskuddsgaranti gjør det mer lønnsomt å velge prosjekter med unødvendig

Dersom alle banker går får en slik løsning  Systemrisiko.

- Høyere egenkapitalkrav til bankene vil føre (1)Lavere forventede utbetalinger ved systemrisiko (2) Gradvis substitusjon over fra forretningsmodeller med overdreven risiko.

## Tema 2: Statsgjeld

## Konsolidert budsjettbetingelse for offentlig sektor

Offentlig sektor

$$B_{t}^{f} = (1+i_{t-1})B_{t-1}^{f} + (G_{t} - T_{t}) - SNG_{t}$$

Sentralbanken

$$i_{t-1}B_{t-1}^{m} + \Delta B_{t}^{m} = \Delta M_{t} + SNG_{t}$$

Statsgjeld

$$Bt=Btf−Btm$$

- Ved å kombinere uttrykkene ovenfor, får vi den konsoliderte budsjettbetingelsen for offentlig sektor

$$B_{t} = (1+i)B + (G_{t}-T_{t}) - \Delta M_{t}$$

## Dynamikken i statsgjelden over tid

Ved null inflasjon, $i_{t}=r_{t}$ og $ΔMt=0$ kan uttrykket ovenfor skrives som

$$\frac{B_{t}}{Y_{t}} = \frac{G_{t}-T_{t}}{Y_{t}} + \frac{B_{t-1}}{Y_{t-1}}(1 + r -g)$$


- Grafisk analyse for fire tifeller:

Viktigst:
$(1+r-g)>1$ og (i) $(G_{t}−T_{t})>0$ og (ii) $(G_{t}−T_{t})<0$

Mindre viktig:
$(1+r-g)<1$ (iii) $(G_{t}−T_{t})>0$ og (iv) $(G_{t}−T_{t})<0$

### Mulig tiltak for å forhindre en statsgjeldskrise

- Kutte i primærbudsjettet (øke T eller redusere G)
- Mislighold
- Inflasjon (man må gjøre sentralbanken mindre uavhengig)

## Tema 3: Likviditetsfellen og privat gjeld

### Hva er likviditetsfellen?

- Sitasjon hvor pengepolitikken ikke lengre kan påvirke realøkonomien på en ekspansiv måte: Kortsiktig nominell rente er (nær) lik null.
- Beskrevet først av Keynes i &quot;General Theory&quot; på 1930-tallet. Men blitt aktualisert etter den globale finanskrisen

### Hvordan havner man i en likviditetsfelle?

<!--
-
Case 1: Demografiske endringer (Krugman, 1998) ⇒Δ´C&lt;0
 (eks. spare mere til alderdommen)
 (eks. spare mere til alderdommen)

1−c(1−t)ΔY=1

Likviditetsfelle dersom rentereduksjonen ikke klarer å veie opp for nedgangen i konsumet som er en følge av de demografiske endringene:

ΔC´−b∙Δi0
)&lt;0

1−c(1−t)⇒ΔY=1

-
Case 2: Privat gjeldsreduksjon (Krugman og EggertsSon, 2012)⇒ΔDb&lt;0
 (Minsky moment)
 (Minsky moment)



1−c¯ (1−t)ΔY=1

Likviditetsfelle dersom rentereduksjonen ikke klarer å veie opp for nedgangen i konsumet som er en følge av gjeldsreduksjonen:

 θ∙ΔDb−b¯ ∙Δi0
)&lt;0

1−c¯ (1−t)⇒ΔY=1

-
Likviditetsfelle Y&lt;Yn

T=tY
  går ned. Redusert BNP og redusert skatter 
Bt/Yt
 øker. Gitt at sentralbanken ikke gis muligheten til å øke pengemengden for å kjøpe statsobligasjoner, vil en overgang til en likviditetsfelle lett kunne smitte over i en statsgjeldskrise.
T=tY
  går ned. Redusert BNP og redusert skatter 
Bt/Yt
 øker. Gitt at sentralbanken ikke gis muligheten til å øke pengemengden for å kjøpe statsobligasjoner, vil en overgang til en likviditetsfelle lett kunne smitte over i en statsgjeldskrise.
  går ned. Redusert BNP og redusert skatter Bt/Yt
 øker. Gitt at sentralbanken ikke gis muligheten til å øke pengemengden for å kjøpe statsobligasjoner, vil en overgang til en likviditetsfelle lett kunne smitte over i en statsgjeldskrise.
 øker. Gitt at sentralbanken ikke gis muligheten til å øke pengemengden for å kjøpe statsobligasjoner, vil en overgang til en likviditetsfelle lett kunne smitte over i en statsgjeldskrise.

## Hvordan komme ut av en likviditetsfelle?

- Den lukkede økonomi modellen forteller oss at finanspolitikken kan betraktes som en gratis lunsj:

1. (1)Vil kunne lukke produksjonsgapet.
2. (2)Vil stabilisere prisene
3. (3)Rentekostnader ved å gjøre dette vil være (tilnærmet) lik null.

- For en åpen økonomi er ikke situasjonen like enkel.  Dette vil bli forklart nærmere under forelesningen om krisen i eurosonen.

-->
