---
output: html_notebook
---

```{r include=FALSE}
library(MakroOEKB1115)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(grid)
library(latex2exp)
```

## Grunnleggende  bakgrunnkunnskaper

### Stabiliseringsmål for en åpen økonomi

- Intern balanse (lukke produksjonsgapet):

$$(Y-\overline{Y})=0$$

- Ekstern balanse (rimelig nivå på utenlandsgjelden - utenlandsgjelden skal kunne betjenes uten problemer)

### Tre fundamentale endringer fra en lukket økonomi:

#### (1) Handel med utlandet

$$AE \equiv C+I+G+NX$$
$NX$ er lagt til definisjonen for aggregert etterspørsel

$$NX=EX−R\cdot IM \text{ hvor } R=\frac{E\cdot P}{P^{*}}$$
Som er definert som eksport $(EX)$ minus import $(R\cdot IM)$. Realvalutakursen $R$ sørger for at alt blir målt i enheter av det innenlandske godet.

#### (2) Utenriksregnskapet

$$BP = CA + CU + OR=0$$

CU=Driftsregnskapet: Nettoeksport ($NX$), Nettofinansinntekter(aksjer og obligasjoner), Nettoverføringer

CA=Kapitalregnskapet: Nettoendringer i fordringer og gjeld ovenfor utlandet

#### (3 Fast eller flytende kurs

- Handel med utlandet (avhenger blant annet av relative prisnivået mellom innenlandske og utenlandske varer)

Realvalutakursen: $R=\frac{EP(dropper $t$ nedenfor fordi vi ser på en statisk modell)(dropper $t$ nedenfor fordi vi ser på en statisk modell)}{P}$

- E: Pris (nominell) per énhet av utenlandsk (innenlandsk) valuta E  (1/E)

- internasjonale finansmarkeder (renteparitetsbetingelsen)

$$(1+i_{t+1})=(1+i_{t+1}^{*})\frac{E_{t+1}^{e}}{E_{t}}$$


### Adferdsligninger

#### Husholdninger og bedrifter

Husholdningene import ($IM$) av utenlandske goder er gitt ved

$$IM=  -m_{1}R + m_{2}Y $$

Bedriftenes eksport ($EX$) av innenlandske goder er gitt ved

$$EX=x_{1}R + x_{2}Y^{*}  $$

Ved å sett inn for uttrykkene ovenfor, kan vi skrive nettoeksporten som  

$$NX = EX - IM = x_{1}R + x_{2}Y^{*} + m_{1}R - x_{2}Y$$

Legger til grunn i dette kurset at $\frac{\Delta NX}{\Delta R}/>0$  (i praksis kan dette ta litt tid)

#### Offentlige myndigheter

Myndighetene kan velge mellom fast (troverdig) eller flytende kurs:

- Fast (troverdig $⇒E=E_{e}$): 

$$i =i^{*}$$

- Flytende 

$$E=\frac{(1+i)}{(1+i)}E^{e}$$

### Mundell-Fleming modellen

#### Fast kurs

#### Flytende kurs

#### Komparativ statikk (skiftanalyse)

#### Stabiliseringspolitikk 
- Finanspolitikk
- Pengepolitikk

### AD-AS modellen for en åpen økonomi

#### Komparativ statikk (skiftanalyse)

#### Stabiliseringspolitikk 
- Finanspolitikk
- Pengepolitikk




<!--
- 
1. $$Y = \frac{1}{1-c-R?}  \left [ \overline{C} -c\cdot \overline{T} - b\cdot \overline{i} + \overline{G}  \right ]$$
1. $$\frac{M}{P}=\kappa\cdot Y + h\cdot i$$
1. $$E = \frac{1+i^{*}}{1 + i} \text{ Flytende kursregime}$$
1. $$i = i^{*} \text{ Fastkursregime}$$

- IS-kurven under fast og flytende kurs

Generelt fører lavere rente til høyere produksjon.

Men multiplikatoren blir mindre ved en åpen økonomi, grunnet importlekkasje.

Helningen på kurven er slakere under flytende kurs enn med fast kurs. Det skyldes at lavere rente under flytende kurs fører til en depresiering av den nominelle og realvalutakursen, noe som forbedrer landets konkurranse evne og dermed fører til økt etterspørsel gjennom økt nettoeksport.

- LM modellen stigende under fast og horisontal under fast(?)

- Skiftanalyse (grafisk og verbalt)

Merk: P gir AS-kurven.

- Stabiliseringspolitikk (grafisk og verbalt)

Virkemidler: $G$, $T$ og $M/i$
 (Flytende) og
$G$,$T$ og($E$)
 (Fast kurs)
 

### Mundell-Fleming (IS-LM for en åpen økonomi) modellen 

- AS-kurven samme som under en lukket økonomi.
- AD-kurven er fallende ved at økt priser fører til lavere etterspørsel.
- Sentralt poeng med modellen – Selvkorrigerende mekanismer:

Fleksibilitet i P og korrekte prisforventninger Pe
på sikt, fører til at økonomien på sikt går tilbake til sin naturlige produksjons- og ledighetsnivå.
