---
bibliography: pensum.bib
---

## Introduksjon til økonomisk vekst

- Vi er opptatt av økonomisk vekst i et land,  fordi dette øker velstandsnivået blant landets innbyggere over tid

- Det er vanlig å måle et lands velstandsnivå ved å dele BNP $Y$ på antall innbyggere i landet $N$, dvs $Y/N$

- Målinger av dette finner for de fleste land i verden:  [tabell fra Wikipedia](https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(PPP)_per_capita)

---

### Empiriske observasjoner over tid

- Rike land: Har vokst og BNP per innbygger mellom land har konvergert (dvs. mindre forskjeller).
    + Prediksjonen er i tråd med Solow-modellen for økonomisk vekst
    
- Fattige land: Finner ingen slik klar sammenheng
    + Hypoteser: (1) Geografi, (2) Kultur, **(3) Institusjoner**

---

###  Inklusive og ekstraktive offentlige institusjoner [@acemoglu2013nations]

Institusjonene kan kalles **ekstraktive** ved at en elite benytter disse til å ekstrahere verdier fra flertallet. 

Institusjonene kan kalles **inklusive** dersom de sørger for privat eiendomsrett, borgerrettigheter, upartisk 
rettsvesen, fri etableringsrett og karrierevalg

Øvelse: Les artikkelen [Venezuela Is Starving Its People](artikler/del2_venezuela.pdf) og noter ned de eksemplene du finner på ekstraktive institusjoner 

---

## Solow-modellen for økonomisk vekst 

Solow-modellen bygger på forutsetninger om sterk grad av **inklusive** institusjoner. 
<!--
Mer konkret kan vi uttrykke disse som:
- Abc
- Def
-->
