---
# ØKB1115 Makroøkonomi

## Gjelder for studieåret 2017/2018

### Innhold
    
### Læringsutbytte
#### Kunnskaper
- Enkel Keynes-modell med og uten internasjonal handel  
- IS-LM og Mundell-Fleming modellen  
- AD-AS modell under lukket og åpen økonomi (fast og flytende valutakurs) 
- Stabiliseringspolitikk
- Solows vekstmodell.
- Pengesystemet (innvendige og utvendige penger)
- Formålet med bankreguleringer 
- Statsgjeldskrise
- Likviditetsfellen som en konsekvens av demografiske endringer og privat gjeldsreduksjon

#### Ferdigheter
- Være i stand til å lese avanserte avisartiker (eks. Wall Street Journal) om makroøkonomiske spørsmål 
- Foreta begrensede utredninger av makroøkonomiske spørsmål, og konsekvenser av makroøkonomiske endringer for næringslivet, bedriftene og enkeltmennesker. 
- Vurdere økonomiske utredninger, f.eks. stortingsmeldinger, NOU-utredninger m.m. 

#### Generell kompetanse
- Samfunnsengasjement.
- Forstå egeninteressen til ulike økonomiske agenter.
- Analytisk holdning med vekt på saklighet og objektivitet.

### Arbeidsformer
Forelesning og oppgaveløsning
 
### Forkunnskaper
Ingen

### Anbefalte forkunnskaper
Grunnleggende matematikk

### Obligatoriske arbeidskrav
Ja, spesifiseres i semesterplan ved semesterstart

### Vurdering
Skriftlig skoleeksamen, 4 timer, 100%.

Karakterskala A-F, der F tilsvarer ikke bestått.

### Hjelpemidler ved eksamen
Skolens kalkulator
<!--



Nasjonalregnskap og makroøkonomiske data
Mundell-Fleming for en åpen økonomi
Arbeidsmarkedet
Modell for aggregert tilbud og etterspørsel (SAS-DAD)
Økonomisk politikk
Læringsutbytte
Kunnskaper

Kurset tar mål om at studenten skal

Kjenne grunnleggende makroøkonomiske data fra nasjonalregnskapet.
Kjenne andre sentrale makroøkonomiske data som prisindekser og tall for arbeidsledighet og sysselsetting.
Kjenne grunnleggende teorier for etterspørselen etter et lands varer og tjenester.
Kjenne til grunnleggende Keynesiansk teori slik den fremkommer i modellen Mundell-Fleming for en åpen økonomi.
Kjenne til hvordan penge- og finanspolitikk påvirker samlet etterspørsel.
Kjenne til norsk penge- og finanspolitikk.
Kjenne hovedteorier for hvordan arbeidsmarkedet og lønnsfastsettelsen fungerer.
Kjenne teorier for hvorfor vi har arbeidsledighet.
Kjenne hvordan interaksjonen mellom tilbudet og etterspørselen skaper konjunkturer og påvirker inflasjonen og lønningene ved bruk av en modell.
Kjenne pengepolitikkens transmisjonskanaler og forstå hovedtrekkene i hvordan disse fungerer.
Ferdigheter

Studentene skal ved endt kurs kunne

Finne frem til og tolke økonomiske data.
Anvende Mundell-Fleming til å forstå hvordan ulike hendelser påvirker aggregert etterspørsel. De skal forstå hvordan vi kan bruke penge- og finanspolitikken for å stabilisere økonomien.
Anvende en modell for aggregert tilbud og etterspørsel for å forstå konjunkturer og virkningen av inflasjonsmålet.
Mer generelt kunne tilegne seg makroøkonomiske nyheter og analyser og tolke de innenfor makroøkonomisk teori.
Generell kompetanse

Gjøre bruk av abstrakte modeller
Beherske grunnleggende begreper og analyse
Reflektere kritisk over økonomiske hendelser
Arbeidsformer
 Forelesning og oppgaveløsning

Forkunnskaper
 Ingen

Anbefalte forkunnskaper
Grunnleggende matematikk

Obligatoriske arbeidskrav
Ja, spesifiseres i semesterplan ved semesterstart

Vurdering
Skriftlig skoleeksamen, 4 timer, 100%.

Karakterskala A-F, der F tilsvarer ikke bestått.

Hjelpemidler ved eksamen
Skolens kalkulator



```{r eval=FALSE, include=FALSE}

Medvirkende lærere
Jørn Inge Halvorsen 
Strukturert undervisningstid
2*2 timer forelesninger og øvinger per uke 
Obligatoriske undervisningsaktiviteter
-
Overlapping og studiepoengreduksjon
ECN220 - 5 stp 
Forutsatte forkunnskaper
ECN 120 og ECN122 eller tilsvarende emne. 
Anbefalte forkunnskaper


Eksamensform
S
Eksamen
-
Karakterregel
A-F
Hjelpemidler ved skriftlig eksamen
B1: utdelt kalkulator, ingen andre hjelpemidler
Normert arbeidsmengde
300 timer 
Emnefrekvens
Årlig
Frekvenskommentar
-
Læringsmåter
Emnet kombinerer forelesninger, øvingsoppgaver, obligatorisk gruppeoppgave, klassediskusjoner, samt omfattende nettside med bl.a. linker til økonomisk litteratur, økonomiske institusjoner. 
Læringsstøtte
-
Sensor
Ekstern sensor kvalitetssikrer pensum, eksamensoppgaver og prinsipper for evaluering og besvarelser. 
Opptakskrav
GSK
Fortrinnsrett
-
Emnet tilbys første gang
2013 høst



Eksamen: 
Midtveis i kurset vil det bli gitt en obligatorisk innleveringsoppgave. Denne må bli godkjent for at kandidaten skal kunne gå opp til skriftlig eksamen.

 
 
Merknad
 
Et tilsvarende emne i makroøkonomi undervises ved mange andre universiteter og høgskoler i Norge og andre land. Men dette kurset inkluderer også nyere og mer dagsaktuelle temaer som finansiell ustabilitet, reguleringer av banker og om bruk av ukonvensjonelle pengepolitikk.




 
Mål
 
Kandidater fra emnet skal ha kunnskaper og innsyn i sentrale makroøkonomiske modeller og temaer som: 
* Enkel keynesianske multiplikator-modeller. 
* IS-LM for lukket og åpen økonomi. 
* AD-AS for lukket og åpen økonomi. 
* Stabiliseringspolitikk.
* Stilisert fakta om økonomisk vekst  og Solows vekstmodell.
* Årsaker til finansiell ustabilitet og dype økonomiske kriser. 
* Ukonvensjonelle pengepolitikk: Bruka av kvantitative lettelser og refinansierngslån.
* Budsjettbetingelsen for offentlig sektor.
* Formålet med bankreguleringer. 
* Sammenheng mellom statlig og privat gjeldskrise.


Med kunnskaper om disse modellene og temaene skal kandidatene kunne: 
- foreta begrensede utredninger av makroøkonomiske spørsmål, og konsekvenser av makroøkonomiske endringer for næringslivet, bedriftene og enkeltmennesker. 
- vurdere økonomiske utredninger, f.eks. stortingsmeldinger, NOU-utredninger m.m. 

Emnet skal, som andre økonomiemner, øke kandidatenes: 
- samfunnsengasjement.
- forstå egeninteressen til ulike økonomiske agenter.
- analytisk holdning med vekt på saklighet og objektivitet.
 
 
Innhold
 
Del 1: Kortsiktig makro: Konjunkturanalyse og stabiliseringspolitikk. 
Del 2: Økonomisk vekst: Stilisert fakta og Solows vekstmodell. 
Del 3: Spesialtemaer: (1) Penger, kreditt og bankadferd (2) Statsgjeld (3) Likvidietsfellen og privat gjeld 
Del 4: Appliasjon: Krisen i eurosonen.




 
Pensum
 
Utvalgte deler av: Blanchard, Olivier: "Macroeconomics" (siste utgave). 
Forelesningsnotater .


```

-->
