#Oversikt over fagett
- Tre hovedtemaer: 
    1. Konjunktursvingninger
    1. Økonomisk vekst
    1. Økonomiske kriser

- Tilknyttet dette ønsker vi å undersøke
    + Hva forårsaker konjunktursvingninger, økonomiske vekst og økonomiske kriser
    + Hvilken rolle bør offentlige myndigheter spille
    
- Sentral økonomer i makroøkonomi som har gitt vesentlige bidrag til å besvare disse spørsmålene:
    + Keynes (1883-1946) / Krugman(1953-)
    + Friedman (1912-2006)
    + Minsky (1919-1996)
    + Hayek (1899-1992) 
    
- Aktørene i økonomien:
    + Husholdninger 
    + Bedrifter 
    + Finansinstitusjoner 
    + Sentralbanken 
    + Offentlige myndigheter

- Markedene: 
    + Vare- og tjenestemarkedet
    + Pengemarkedet 
    + Arbeidsmarkedet
    + Finansinstitusjoner (investering- og forretningsbanker) 
    + Valutakursmarkedet.

- To typer økonomier:
    + Lukket (eller globalisert) økonomi
    + Åpen økonomi
    
#Del 1
##Grunnleggende bakgrunnskunnskap
- Bruttonasjonalprodukt (GDP/BNP)

- Bruttonasjonalinntekt (GNP/BNI)

- Nominell BNP ($LY$)
$$LY = PY$$
- Reel BNP
$$Y = \frac{LY}{P}$$

- Arbeidsledighetsrate:

$$u = 1-\frac{L}{N}$$

- Inflasjon 

$$\pi = \frac{\Delta P}{P} =\frac{P_{t} - P_{t-1}}{P_{t-1}}$$

- Okuns lov:
negativ korrelasjon mellom endring i arbeidsledighet og vekst BNP 

- Phillips-kurven:
negativ sammenheng mellom arbeidsledighet og endring i inflasjon

- Hvordan bestemmes BNP?
    + Kort sikt
    + Mellomlang sikt
    + Lang sikt

## Lukket økonomi
Aggregert etterspørsel (AE) i en lukket økonomi    

$AE \equiv C + I + G$

### Likevekt i godemarkedet (varer og tjenester)

Hvor vi postulerer følgene adferdlikginger

- Husholdningene:
$$C = \overline{C} + c(Y-T)$$
- Bedriftene:
$$I = \overline{I} - b\cdot i$$

- Sentralbanken
$$i = \overline{i}$$

- Offentlige myndigheter
$$G = \overline{G}$$  
$$T = t\cdot Y$$ 

Løser denne modellen mhp. på Y gir oss IS-likningen (kombinasjoner av i og Y som er forenlig med likevekt i varemarkedet)

$$Y = \frac{1}{1-c}  \left [ \overline{C} -c\cdot \overline{T} - b\cdot \overline{i} + \overline{G}  \right ]$$

Skiftanalyse (matematisk, figur, og verbalt): Eks. endring i $\Delta Y$ som følge av en økning i $\Delta \overline{I}$:

- Matematisk:

$$\Delta Y = \frac{1}{1-c}\Delta  \overline{I}>0 \text{ eller } \frac{\Delta Y}{\Delta  \overline{I} } = \frac{1}{1-c}>1$$

- Figur: (se notater)

- Verbalt  (dynamisk forklaring utenfor modellen):
Økte investeringer $\rightarrow$ økt produksjon $\rightarrow$ initierer en multiplikatoreffekt: $\rightarrow$ økt disponibel inntekt $\rightarrow$ økt konsum $\rightarrow$ økt produksjon osv.

Stabiliseringspolitikk: $\Delta G <0$

$$\Delta Y = \frac{1}{1-c}  \left [ \Delta \overline{I} + \Delta \overline{G} \right ]$$

Dersom vi lar $\Delta \overline{I} = - \Delta \overline{G} > 0 \Rightarrow \Delta Y = 0$ (dvs. intern balanse)

### Likevekt i pengemarkedet 
- Tilbudet av penger ($M^{s}$)

Ser foreløpig kun på utvendige penger: Sedler og mynt pluss reserver. Dette nivået blir bestemt av sentralbanken
$\overline{M}/P$

- Etterspørsel etter penger:
$$L_{d} = \kappa Y -hi$$

- Likevekt i pengemarkedet: 
$$M/P = L_{d}$$  

Sentralbanken bestemmer hva som skjer i pengemarkedet ved
(1) Endre tilbudet av penger (vanlig tidligere) eller (2) å endre rentenivået (vanlig i dag).

## IS-LM modellen for en lukket økonomi: Gode- og pengemarkedet i likevekt

- Varemarkedet

$$Y = \frac{1}{1-c(1-t)}  \left [ \overline{C} -c\cdot \overline{T} - b\cdot \overline{i} + \overline{G}  \right ]$$
$\Rightarrow$ IS-kurven

$$\Delta Y =\left[\frac{-b}{1-c(1-t)}\right ]   \cdot \Delta \overline{i}<0$$
- Pengemarkedet
$$kY -hi = \overline{M}/P$$
$\Rightarrow$ LM-kurven

$$\Delta Y =\left[\frac{-b}{1-c(1-t)}\right ]   \cdot \Delta \overline{i}<0$$

- Grafisk tegning bestemmer her $i$ og $Y$ samtidig

- Skiftanalyse (grafisk og verbalt)
Merk: P gir AD-kurven

- Stabiliseringspolitikk (grafisk og verbalt)
Virkemidler: $G, T, M/i$

### AD-AS modellen for en lukket økonomi: Gode, penge og arbeidsmarkedet i likevekt

- Husholdningene: Tilbyr arbeid

$$W=P^{e}F(\underset{(-)}{u}, \underset{(+)}{z})$$

- Bedrifter: Etterspør arbeidskraft og tilbyr produktet i et marked med monopolistisk konkurranse

$$Y=AL$$

$$P=(1+μ)W$$

- Ledighet

$$u=\frac{U}{N}=\frac{N-L}{N}=1−\frac{L}{N}=1−\frac{Y/A}{N}=1 - \frac{Y}{AN}$$

- Kombinere dett gir oss AS-kurven (verdier av P og Y som gir likevekt i arbeidsmarkedet)

$$P=(1+μ)P^{e}F(1 - \frac{Y}{AN},z)$$

- AD-AS-modellen

$$Y = \frac{1}{1-c}  \left [ \overline{C} -c\cdot \overline{T} - b\cdot \overline{i} + \overline{G}  \right ]\text{ :Godemarkedet}$$ 

$$\frac{\overline{M}}{P}=\kappa Y - h\cdot i  \text{ :Pengemarkedet}$$

$$P=(1+μ)P^{e}F(1−\frac{Y}{AN},z) \text{ :Arbeidsmarkedet}$$ 

Merk: $P=Pe⇒Y=Yn=u=un$: Naturlige produksjons- og ledighetsnivået,

Grafisk tegning bestemmer her P, Y
og i samtidig

- Skiftanalyse (grafisk og verbalt)
- Stabiliseringspolitikk (grafisk og verbalt)

Virkemidler: $G$, $T$ og $M/i$

- Sentral poeng med modellen – Selvkorrigerende mekanismer:

Fleksibilitet i P og korrekte prisforventninger Pe
 på mellomlang sikt, fører til at økonomien går tilbake til sitt naturlige produksjons- og ledighetsnivå.

### IS-LM modellen for en åpen økonomi: Gode-, penge- og valutakursmarkedet i likevekt

- To stabiliseringsmål:

1. Intern balanse (produksjon lik naturlig produksjonsnivå)

1. Ekstern balanse (rimelig nivå på utenlandsgjelden)

- Tre fundamentale endringer fra en lukket økonomi:

1. Handel med utlandet

1. Fast eller flytende kurs

1. Internasjonale finansmarkeder


$$AE = C+I+G+NX$$

$$ NX=EX−R∗IM    $$

$$ BP = CA + CP + OR=0 $$

CU=Driftsregnskapet: Nettoeksport, Nettofinansinntekter(aksjer og obligasjoner), Nettoverføringer

CA=Kapitalregnskapet: Nettoendringer i fordringer og gjeld ovenfor utlandet

- Handel med utlandet (avhenger blant annet av relative prisnivået mellom innenlandske og utenlandske varer)

Realvalutakursen: $R=\frac{EP}{P}$

- E: Pris (nominell) per enhet av utenlandsk (innenlandsk) valuta E  (1/E)

- Postulerer følgende adferdsligninger for handelsbalansen

$$IM=X(\underset{(-)}{R}, \underset{(+)}{Y}) =  -m_{1}R + x_{2}Y $$
$$EX=X(\underset{(+)}{R}, \underset{(+)}{Y^{*}}) = x_{1}R + x_{2}Y^{*}  $$

Det betyr at

- $$NX = EX - IM = x_{1}R + x_{2}Y^{*} + R(-m_{1}R + x_{2}Y)$$

Legger til grunn (i praksis kan dette ta litt tid) i dette kurset at $\frac{\Delta NX}{\Delta R}>0$ (depresiering av realvalutakursen forbedrer nettoeksporten) 

- internasjonale finansmarkeder (renteparitetsbetingelsen)

$$(1+i_{t+1})=(1+i_{t+1}^{*})\frac{E_{t+1}^{e}}{E_{t}}$$

- Myndighetene kan velge mellom fast eller flytende kurs

Fast: 

$i =i^{*} + rp$

Troverdig kurs vil si at $E=E_{e} \Rightarrow rp=0$

Flytende: 

$E=\frac{(1+i)}{(1+i)}E^{e}$ 

- Modellen
1. $$Y = \frac{1}{1-c-R?}  \left [ \overline{C} -c\cdot \overline{T} - b\cdot \overline{i} + \overline{G}  \right ]$$
1. $$\frac{M}{P}=\kappa\cdot Y + h\cdot i$$
1. $$i = i^{*} + rp \text{ Fastkursregime}$$
1. $$E = \frac{1+i^{*}}{1 + i} \text{ Flytende kursregime}$$

<!--

- IS-kurven under fast og flytende kurs


Generelt fører lavere rente til høyere produksjon.

Men multiplikatoren blir mindre enn ved en lukket økonomi, grunnet importlekkasje.

-->
<!--


Helningen på kurven er slakere under flytende kurs enn med fast kurs. Det skyldes at lavere rente under flytende kurs fører til en depresiering av den nominelle og realvalutakursen, noe som forbedrer landets konkurranse evne og dermed fører til økt etterspørsel gjennom økt nettoeksport.

- LM modellen stigende under fast og horisontal under fast(?)

- Skiftanalyse (grafisk og verbalt)

Merk: P gir AS-kurven.

- Stabiliseringspolitikk (grafisk og verbalt)

Virkemidler: $G$, $T$ og $M/i$
 (Flytende) og
$G$,$T$ og($E$)
 (Fast kurs)
 

### Mundell-Fleming (IS-LM for en åpen økonomi) modellen 

- AS-kurven samme som under en lukket økonomi.
- AD-kurven er fallende ved at økt priser fører til lavere etterspørsel.
- Sentralt poeng med modellen – Selvkorrigerende mekanismer:

Fleksibilitet i P og korrekte prisforventninger Pe
på sikt, fører til at økonomien på sikt går tilbake til sin naturlige produksjons- og ledighetsnivå.
-->
