# Del I: Konjunktursvingninger
## Seminar 1: Datatransformering av nasjonalregnskapstall

### Installering av FRED applikasjon til Excel
- Installer applikasjonen FRED (fra Federal Reserve Bank of St. Louis)  i ditt Excel regneark [Windows](https://research.stlouisfed.org/fred-addin/install_windows.html) og [Mac](https://research.stlouisfed.org/fred-addin/install_mac.html)

- Hjelp og tips til bruk av programmet finnes her:
[Youtube](http://www.youtube.com/watch?v=OAH-wGtP_k8)

- Har du problemer med installeringen med applikasjonen, er en annen framgangsmåte at du søker opp tallene direkte ved bruk av denne [lenken](https://fred.stlouisfed.org/). Etter at du gjort bruk av søkefeltet, klikker du på den tidsserien du ønsker å benytte. I det nye vinduet som da åpner seg har du mulighet til å laste ned (download-knappen) tidsserien som Excel-fil (merk: edit graph-knappen gir deg mulighet til å velge ulike frekvenser for tidsserien)   


### Tidsserier
Gjør følgende oppgaver for Norge, Tyskland og enten for Hellas, Italia, Portual eller Spania 

- Hent tidsserien til bruttonasjonalproduktet i real størrelser
- Transformer denne serien ved å ta logaritmen 
- Hent en tidsserie for arbeidsledighet 
- Hent en tidsserie for konsumprisindeksen 
- Vis tidsseriene grafisk
- Gir serien noen indikasjoner på dype økonomiske kriser?  Hvis ja, se om du kan finne (ved søk på internett) noen kortfattede økonomiske forklaringer bak disse krisene

### Okuns lov og Phillips-kurven
- Finn et mål på inflasjon (årlig)
- Finn et mål på ledighet (årlig)
- Lag et scatterplot for endring i ledighet og vekst i BNP (Okuns lov)
- Lag et scatterplot for ledighet og endring i inflasjon (Phillips-kurven).
- For de to scatterplottene, se om du klarer å estimere en linje (dvs. finn korrelasjonskoeffisienten) for graden av lineær korrelasjon
- Er resultaten du finner i tråd med de empirisk regularitetene som ble diskutert i forelesningen?
