---
output:
  html_notebook:
    css: seminarPAA.css
---

# Obligatorisk oppgave: 
Modellen er gitt ved


## Del 1:
1. Hva mente Keynes med begrepet 'Animal spirits'? 
1. Hvorfor ønsket Milton Friedman en pengepolitisk regel som innebærer en konstant vekst i pengemengden?
1. Hvilken to stabiliseringsmål gjelder for en liten åpen økonomi og hvorfor tar det vanligvis lengre tid oppnå disse to målende i et fastkursregime vs. flytende kurs-regime?
1. Hvilke markeder er operasjonelle for AD-AS modellen for en åpen økonomi under flytende kurs?
1. En liten åpen økonomi har et prisnivå som oppfyller inflasjonsmålet, men så plutselig blir inflasjonsmålet senket og sentralbankens mandat tilsier at de med dette må øke etterspørselen i økonomien. Hvordan påvirker dette rente og valutakursen på kort sikt (hint: ta utgangspunkt i likevektsløsningen som gjelder for penge- og valutkursmarkedet)?
1. Sett opp løsningen for en Keynes modell i en liten åpen økonomi hvor det er satt en tollsats  ($\tau$) på
prisen fra utlandet. Anta videre at tollen på importvarer ($\tau$) fra utlandet øker. Forklar verbalt hvordan dette påvirker produksjonen og inntekten i økonomien. 
#E. Tror du etterspørselseffekten endres dersom vi har med en åpen økonomi og hvorfir ikke

## Del 2:  AD-AS lukket økonomi
Tar utgangspunkt i følgende modell

1. Stil opp modellen
1. Skift i både G og T
1. Uten teknologi
1. Abc
1. Def
1. Med teknologi
1. Ghi
1. Jhi

## Del 3: Statsgjeld
1. Vis ved utregning hvordan man kommer frem til den konsoliderte budsjettbetingelsen for offentlig sektor. I 
utgangspunktet har vi
(@abc) 
$$B^f_t= \underset{\text{a}}{(1+i_{t})B^{f}_{t-1}}+\underset{\text{det primære budsjettunderskudd}}{(G_t-T_t)} - \underset{Seniorage}{SNG_t}$$

(@def)
$$ B_{t-1}\cdot i_{t-1} + \Delta B_{t}^{m} = \Delta M_{t}$$
(@ghi)
$$B_{t} = B_{t}^{f} - B_{t}^{m}$$

*Starter med*

*B^f_t= (1+i_{t})B^{f}_{t-1}+{(G_t-T_t)} - SNG_t*

*$$B^f_t= \underset{\text{a}}{(1+i_{t})B^{f}_{t-1}}+\underset{\text{det primære budsjettunderskudd}}{(G_t-T_t)} - \underset{Seniorage}{SNG_t}$$*



1. Figur vis fase-diagram lav produktivitet (g>r) og forklar dynamikken
1. Figur vis fase-diagram høy produktivitet (g<r) og forklar dynamikken
1. Diskuter kort virkemidler for å komme seg ut av av statsjgeldskrise, både i en situasjon med og uten en uavhengig sentralbank

Ligning @abc

<!--

# Obligatorisk oppgave: 
## Del 1
1. I makroøkonomi antas produksjonen (BNP) på kort sikt å være bestemt av etterspørselen. Hvilken sentral forutsetning ligger til grunn for dette resultatet?
Svar: Stive priser.
2. Helningen på IS-kurven under en åpen økonomi med flytende valutakurs kan forklares av fire faktorer, beskriv disse.
Svar: (1)+ Lavere rente gir økt investeringer og/eller økt konsum. (2)+ Multiplikatoreffekt:  Økt etterspørsel gir økt inntekt og dermed økt konsum etc.  (3)- Importlekkasje og (4) lavere rente gir lavere realvalutakurs som gir økt nettoeksport.
3. Under AD-AS modellen for en åpen økonomi med flytene kurs, hvilke markeder er operasjonelle?
Svar: Varemarkedet, Arbeidsmarkedet, Pengemarkedet og Valutakursmarkedet.
4. Hva menes med intern og ekstern balanse?
Svar: Intern balansen er produksjon (arbeidsledighet) lik det naturlige produksjonsnivået (arbeidsledighetsnivået). Ekstern balanse har vi når hutelandgjelden er på et rimelig nivå (betjenes uten problemer).
5. Hvilke to faktorer anses for å være sentrale når det gjelder skape økonomisk vekst, og nevn noen tiltak myndighetene kan ta i bruk for å oppmuntre til dette?
Svar: (1) Kapitalakkumulasjon – sparing(+), befolningsvekst(-). (2) Teknologisk framgang – institusjoner, lover og regler etc.
6. Hva forstås med innvendige og utvendige penger?
Svar: Utvendige penger er den delen av pengemengden som sentralbanken skaper, består av reserver og sedler og mynt. Innvendige penger er den delen av pengemengden som bankene skaper 

## Del 2 Lukket økonomi
### IS-LM modellen
### AD-AS modellen (lukket)
1. Skift i LAS-kurven

## Del 3: Åpen økonomi
### Mundell-Fleming modellen
#### Fast
#### Flytende

### AD-AS modellen  (åpen)
#### Fast
#### Flytende
