---
output: html_notebook
---
# Seminar 2
## Keynes-modell for en lukket økonomi

Vi ser for oss en lukket økonomi hvor aggregert etterspørsel (AE) er gitt ved
$$AE\equiv C + I + G$$

Hvor $C$ er konsum, $I$ private realinvesteringer og
$G$ offentlig forbruk.

I tillegg postulerer vi følgende adferdsligninger for aktørene i økonomien:
$$C = \overline{C} + c_{1}(Y-T) - c_{2}\cdot i \text{ :Husholdningen}$$
$$I = \overline{I} - b\cdot i \text{ :Private realinvesteringer}$$
$$i = \overline{i} \text{ :sentralbanken}$$
$$G = \overline{G} \text{ og } T=\overline{T} \text{: offentlige myndigheter}$$ 


1. Er det produksjonen $Y$ som bestemmer etterspørselen $AE$, eller etterspørselen $AE$ som bestemmer produksjonen $Y$ i denne modellen?

*På kort sikt er det etterspørselen som bestemmer produksjonen i et lands økonomi*

2. Hvilken sentral forutsetning ligger til grunn for dette resultatet?

*Produktprisen i modellen er konstante (stive)*

3. Gi en økonomisk tolkning tilknyttet konsumfunksjonen til husholdningen.

- *$\overline{C}$ Konsum som blir gitt uavhengig av verdien på de andre variablene i modellen.*
- *$c(Y-T)$ forteller oss hvorstor andel av disponinbel inntekt som går til konsum*
- *$c_{2}\cdot$ gir rentenivåets påvirkning på konsumet. Høyere rente fører til mindre konsum, dette fordi husholdingen ønsker å spare mer når rente øker*

4. Løs modellen mhp. på $Y$.

- *$$Y = \frac{1}{1-c_{2}}\left[\overline{C}-c_{1}\overline{T} - (b+c_{2})\cdot i + \overline{I} + G  \right] $$*

5. Økt pessimisme i økonomien gir seg utslag i et lavere inntektsuavhengig konsum ($\overline{C}>0$). Hvis formelt, grafisk (dersom du ønsker å benytte Keyneskrysset) og verbalt hvordan dette endrer likevekten i modellen.

- Formelt: $$ -\frac{\Delta Y}{\Delta \overline{C}} = \frac{-1}{1-c_{1}} > 0$$

- Keyneskrysset 

- Verbalt: Redusert konsum medfører først redusert aggregert etterspørsel og dermed også  produksjon og inntekt. Den reduserte inntekten initierer en multiplikatoreffekt, siden redusert inntekt medfører redusert konsum, etterspørsel, produksjon og inntekt osv.    


6. Vis formelt (ved differensiering) hvilke stabiliseringspolitiske virkemidler det offentlige har tilgjengelig for å motvirke den økte pessimismen. Hvilken av disse tiltakene vil ha sterkest negativ effekt på statsbudsjettet?

- *Økte offentlige utgifter*

$$\Delta Y = \ \frac{1}{1-c_{1}}\left[\Delta \overline{C} + \Delta {G}  \right]=0 \Rightarrow \Delta \underset{(-)}{\overline{C} }=- \Delta \underset{(+)}{G}   $$

- *Reduserte skatter*

$$\Delta Y = \ \frac{1}{1-c_{1}}\left[\Delta \overline{C}-c_{1} \Delta \overline{T}    \right] \Rightarrow 
\Delta \underset{(-)}{\overline{C}} = c_{1} \Delta \underset{(-)}{\overline{T}}$$

*Underskuddet på statsbudsjettet er gitt ved $G-T$* (offentlige utgifter min skatteinntekter) 

Utgiftsøkningen vil være på $\Delta \overline{C}$, mens skatteinntekten vil måtte reduseres ved
$\Delta \overline{C}/c_{1}$. Siden $\Delta \overline{C} < \Delta \overline{C}/c_{1}$ vil den negative effekten på statsbudsjettet av å gjøre dette ved en skattereduksjon være større enn ved en økning i offentlig utgifter.

Anta at sentralbanken innfører en renteregel som er gitt ved at $i= m\cdot Y$. 

7. Finn nå løsningen til modellen mhp. på Y

*Svar:*

$$Y = \frac{1}{1-c_{1}+m\cdot c_{2} + m\cdot b}\left[\overline{C}-c_{1}\overline{T} + \overline{I} + G  \right] $$

8. Bidrar en slik renteregel til å stabilisere eller dempe konjunktursvingingene (hint: sammenlikn multiplikatoren i de to modellene med hverandre)?

*Vi har at $\frac{1}{1-c_{1}}>\frac{1}{1-c_{1}+m\cdot c_{2} + m\cdot b}$. Siden multiplikatoren er mindre i modellen med renteregel,vil regelen bidra til å dempe effekten eksogenene endringer vil ha på konjunktursvingningene*

## IS-LM modellen

Likvektsbetingelsen for pengemarkedet er gitt ved

$$M^{S} = L_{d}$$

I tillegg til adferdsligningene fra forrige oppgave, har vi her at

$$L_{d} = \kappa\cdot Y - h\cdot i \text{ Husholdningens etterspørsel etter penger}$$


$$M^{s}=\frac{\overline{M}}{P} \text{ :Hvor sentralbanken bestemmer tilbudet av basispenger}$$

1. Vis ved differensiering i et (Y, i) diagram og gi en økonomisk tolkning på hvorfor IS-ligningen er synkende og LM-kurven er stigende 

IS-kurven
$$\frac{\Delta Y}{\Delta \overline{i}} =-\frac{1}{1-c}(b +c_{2})<0$$

- Økt rente gir lavere investeringer og konsum som fører til redusert etterspørsel. Dette initierer en negativ multiplikatoreffekt, fordi redusert etterspørsel medfører 
lavere produksjon og inntekt,  som igjen fører til redusert etterspørsel pga lavere konsum, osv.

LM-kurven finner vi ved å differensiere likevektsbetingelsen for pengemarkedet mhp. Y og i:

$$\frac{\Delta i}{\Delta Y} = \frac{k}{h}>0$$

- Økt inntekt gir økt etterspørsel etter penger pga økt transaksjonsbehov. For at markedet skal være i likevekt, må dette motsvares av et høyere rentenivå

1. Vis ved hjelp av en figur effekten av økt optimisme tilknyttet private realinvestinger ('animal spirits').

1. Vis og forklar verbalt effekten av en reduksjon i prisnivået.

*Blir vist i forelesningen*

1. Vis grafisk hvordan likevekten ser ut i pengemarkedet og IS-LM modellen dersom sentralbanken går over til en renteregel gitt ved  
$i= m\cdot Y$
