# Seminar 2
## Keynes modell for en lukket økonomi

Vi ser for oss en lukket økonomi hvor aggregert etterspørsel (AE) er gitt ved
$$AE\equiv C + I + G$$

Hvor $C$ er konsum, $I$ private realinvesteringer og
$G$ offentlig forbruk.

I tillegg postulerer vi følgende adferdsligninger for aktørene i økonomien:
$$C = \overline{C} + c_{1}(Y-T) - C_{2}\cdot i \text{ :Husholdningen}$$
$$I = \overline{I} - b\cdot i \text{ :Private realinvesteringer}$$
$$i = \overline{i} \text{ :sentralbanken}$$
$$G = \overline{G} \text{ og } T=\overline{T} \text{: offentlige myndigheter}$$ 

1. Er det produksjonen $Y$ som bestemmer etterspørselen $AE$, eller etterspørselen $AE$ som bestemmer produksjonen $Y$ i denne modellen?

1. Hvilken sentral forutsetning ligger til grunn for dette resultatet?

1. Gi en økonomisk tolkning tilknyttet konsumfunksjonen til husholdningen.

1. Løs modellen mhp. på $Y$.

1. Økt pessimisme i økonomien gir seg utslag i et lavere inntektsuavhengig konsum ($\overline{C}>0$). Hvis formelt, grafisk (dersom du ønsker å benytte Keyneskrysset) og verbalt hvordan dette endrer likevekten i modellen.

1. Vis formelt (ved differensiering) hvilke stabiliseringspolitiske virkemidler det offentlige har tilgjengelig for å motvirke den økte pessimismen

1. Anta at sentralbanken innfører en renteregel, som er gitt ved at $i= m\cdot Y$

1. Finn løsningen til modellen mhp. på Y

1. Bidrar en slik renteregel til å stabilisere eller dempe konjunktursvingingene (hint: sammenlikn multiplikatoren i de to modellene med hverandre)?

## IS-LM modellen

Likvektsbetingelsen for pengemarkedet er gitt ved

$$M^{S} = L_{d} $$

I tillegg til adferdsligningene fra forrige oppgave, har vi her at

$$L_{d} = \kappa\cdot Y - h\cdot i \text{ Husholdningens etterspørsel etter penger}$$


$$M^{s}=\frac{\overline{M}}{P} \text{ :Hvor sentralbanken bestemmer tilbudet av basispenger}$$

1. Vis ved differensiering i et (Y, i) diagram og gi en økonomisk tolkning på hvorfor IS-ligningen er synkende og LM-kurven er stigende 

1. Vis ved hjelp av en figur effekten av økt optimisme tilknyttet private realinvestinger ('animal spirits').

1. Vis og forklar verbalt effekten av en reduksjon i prisnivået.

1. Vis grafisk hvordan likevekten ser ut i pengemarkedet og IS-LM modellen, dersom sentralbanken går over til en renteregel gitt ved  
i= m\cdot Y
