---
output:
  html_notebook:
    css: seminar2.css
---

# Seminar 3 (uke 8):
Vi benyttter samme modell som gitt under seminar 2:
$$C = \overline{C} + c_{1}(Y-T) - c_{2}\cdot i \text{ :husholdningen}$$
$$I = \overline{I} - b\cdot i \text{ :private realinvesteringer}$$
$$G = \overline{G} \text{ og } T=\overline{T} \text{: offentlige myndigheter}$$ 

## AD-AS modellen for en lukket økonomi
I tillegg til modellen øverst, har vi her at:

$$AE\equiv C+I+G \text{: aggregert etterspørsel}$$$

$$kY -hi = \overline{M}/P \text{: fra pengemarkedet}$$

$$W=P^{e}F(\underset{(-)}{u}, \underset{(+)}{z}) \text{: lønnsforhandlingene}$$
$$Y=AL^{\alpha}  \text{: produktfunksjonen tilhørende bedriften}$$

$$P=(1+μ)W  \text{: markup-faktor på produktprisene}$$

$$u=\frac{U}{N}=1−\frac{L}{N}  \text{: bestemmer arbeidsledigheten}$$



1. Vis og forklar hvorfor AD-kurven er fallende.
1. Utled og tolk hvorfor AS-kurven stiger i pris når produksjonen øker.
1. Vis at den langsiktige tilbudskurven (LAS) er vertikal (stabilitetsbetingelsen) dersom $P=P^{e}$ (korrekte prisforventninger).
1. Foreta en skiftanalyse i AD-AS modellen som en følge av økte offentlige utgifter.
1. Diskuter fordeler og ulemper ved pengepolitikk vs. finanspolitikk som stabiliseringspolitiske verktøy.

## Keynes-modell for en åpen økonomi
I tillegg til modellen øverst, har vi her at aggregert etterspørsel er gitt ved

$$AE\equiv C+I+G+NX$$
Rente er eksogen satt 

$$i = \overline{i} \text{ :sentralbanken}$$

Hvor nettoeksporten $NX$ er gitt ved

$$NX = EX - R\cdot IM$$

I tillegg postulerer vi følgende adferdsligninger for eksport ($EX$) og import ($IM$)

$$EX = \pm x_{1}\cdot R \pm x_{2}\cdot Y^{*} $$
$$IM= \pm m_{1}\cdot R \pm m_{2}\cdot Y$$
Parameterne $m_{1}$, $m_{2}$, $x_{1}$ og $x_{2}$ er alle positive.

1. Avgjør hvorvidt det skal være pluss eller minus og gi en økonomisk forklaring tilhørende de ulike parameterne tilhørende nettoeksporten

2. Løs modellen hensyn på produksjonen $Y$

3. Sammenlign multiplikatoren med den som du kom fram til under seminar 2 (uten renteregel). Er den mindre eller større? Hva forklarer forskjellen?
