---
output: html_notebook
---
<button type="button"
onclick="document.getElementById('demo').innerHTML = Date()">
Click me to display Date and Time.</button>

# ECN222: Anbefalte oppgaver med løsningsforslag

**Oppgaver gitt til 1. forelesning (4. september)**

Gjør følgende oppgaver for USA, Japan, Norge og (dersom du har tid) minst ett europeisk land.

- Installer applikasjonen FRED i ditt Excel regneark

[http://research.stlouisfed.org/fred2/](http://research.stlouisfed.org/fred2/)

Hjelp til hvordan bruke programmet finnes her:

[http://www.youtube.com/watch?v=OAH-wGtP\_k8](http://www.youtube.com/watch?v=OAH-wGtP_k8)

- Finn tidsserien til bruttonasjonalproduktet i reelle størrelser.
- Finn tidsserien antall innbyggere
- Konstruer tidsserien bruttonasjonalprodukt per innbygger.
- Transformer serien ved å ta logaritmen.
- Vis serien grafisk.
- Gir serien noen tegn på dype økonomiske kriser?  Hvis ja, se om du kan finne (søk på internett) noen kortfattede forklaringer bak disse krisene.
- Finn et mål på inflasjon.
- Finn et mål på ledighet.
- Lag et scatterplot for ledighet og inflasjon (Phillips-kurven).
- Lag et scatterplot for vekst og endring i inflasjon (Okuns lov).

_Svar:_

_Har noen laget et regneark på dette? Send det til_ [_jorn.halvorsen@gmail.com_](mailto:jorn.halvorsen@gmail.com)_,  så vil jeg legge det ut til de andre studentene  i klassen._

**Oppgaver gitt til 2. forelesning**

Kapittel 2, Blanchard, Amighini og Giavazzi

- Question 3.

_Svar:_

_Ble vist i forelesningen._

- Question 4.

_Svar:_

_Ble vist i forelesningen._

**Oppgaver gitt til 3. forelesning**

Ta utgangspunkt i følgende makroøkonomisk modell:

Z=C+I+G

Hvor Z er aggregert etterspørsel. C er konsum. I er private realinvesteringer og G er offentlig kjøp av varer og tjenester.

I tillegg postulerer vi følgende adferdssammenhenger:

C=c0+c1(Y−T)−c2i

I=I−b1i

Hvor T er nettoskatter, i det nominelle rentenivået, og små bokstaver betegner positive parametere.

Likvektsbetingelsen for varmarkedet er gitt ved

Y=Z

Hvor Y betegner produksjonen.

- Nevn tre sentrale forutsetninger som ligger bak en slik modell.

_Svar:_

1. (1)_Stive priser, )(2) Lukket økonomi og (3) produksjon av kun èn vare_

- Finn løsningen til modellen med hensyn på Y.

_Svar:_

_Setter inn for C og I som gir_

Y=c0+c1(Y−T)−c2i+I´−b1i+G

 _Løser uttrykket ovenfor mhp. Y:_

Y(1−c1)=c0−c1T−c2i+I´−b1i+G

Y=1(1−c1)[c0−c1T−c2i+I´−b1i+G]

- Hva skjer når i øker (vis formelt, verbalt og grafisk)?

_Svar:_

_Formelt:_

_Differensiering av_ ΔY _mhp_ Δi _gir_

ΔY=1(1−c1)[−c2Δi−b1Δi]=−1(1−c1)[c2+b1]Δi&lt;0

ΔYΔi=−1(1−c1)[c2+b1]&lt;0

_Grafisk:_

_Se forelesningsnotatene._

_Verbalt:_

_Økte rente_ __ _laver konsum og investeringer_ __ _redusert etterspørsel_ __ _redusert produksjon_ __ _redusert disponibel inntekt_ _ __redusert konsum__ _ _redusert etterspørsel_ __ _redusert produksjon…etc._

-
Anta at sentralbanken innfører en renteregel som tilsier at i=m0Y

_Svar:_

_Ved å sette renteregelen inn for i får vi_

Y=c0+c1(Y−T)−c2m0Y+I´−b1m0Y+G

_Løst mhp. Y gir_

Y(1−c1+c2m0+b1m0)=c0−c1T+I´+G

c(0−c1T+I´+G)Y=1(1−c1+c2m0+b1m0)

- Sammenlikn multiplikatoren i modellen før og etter innføringen av en slik regel. Hvilken er høyest?

_Svar:_

1(1−c1+c2m0+b1m0)&lt;1(1−c1)

_Multiplikatoren blir mindre ved bruk av renteregel._

- Gi en verbal på forklaring på hvordan innførselen av en regel virker inn ved en positiv økning i investeringen

_Svar:_

_Først vil vi ha at:_

_Økt investeringer_ ___Økt etterspørsel_ __ _Økt produksjon_

_Reglen vil ha en stabiliserende effekt, siden vi etter dett vil ha at_

_økt rente ____ reduserte investeringer og konsum___ _Redusert produksjon etc._

- Hva menes med the paradox of thrift?

_Svar:_

_I en IS-LM modell for en lukket økonomi vil det være investeringer være bestemmende for sparingen (S=I). På lengre sikt (jmf. Solow-modellen) vil det være motsatt, dvs. det er  sparinger som er bestemmende for investeringene (dette resultatet er en følge av antagelsen om stive priser)_

**Oppgaver gitt til 4. forelesning**

-
Ta utgangspunkt i samme modell som i forrige oppgavesett. Anta i tillegg nå at pengemarkedet er operativt. Pengetilbudet er derfor gitt vedMs=M
/P og penge etterspørselen
Md=M(Y,i)
.  Vis likevekten i pengemarkedet under forutsetning om at sentralbanken (a) setter rentenivået, (b) bestemmer pengetilbudet.
/P og penge etterspørselen Md=M(Y,i)
.  Vis likevekten i pengemarkedet under forutsetning om at sentralbanken (a) setter rentenivået, (b) bestemmer pengetilbudet.
.  Vis likevekten i pengemarkedet under forutsetning om at sentralbanken (a) setter rentenivået, (b) bestemmer pengetilbudet.

_Svar:_

_Grafisk: Se forelesningsnotatene._

- Bestem Y grafisk under (a) og (b) under forutsetning om at både vare- og pengemarkedet er i likevekt (IS-LM modellen).

_Svar:_

_Grafisk: Se forelesningsnotatene._

- Under (a), hva skjer dersom konsumet øker? Vis grafisk og verbalt.

_Svar:_

_Grafisk: Se forelesningsnotatene._

_Verbalt:_

_Under a)_

_Økt konsum_ __ _økt etterspørsel ____ økt produksjon ____ økt disponibel inntekt___ _økt konsum etc._

_Under b)_

_Økt konsum_ __ _økt etterspørsel ____ økt produksjon ___ _økt rene__ _ _økt disponibel inntekt(men ikke like sterk som under a)___ _økt konsum (men ikke like sterk som under a)  etc._

- Under (b), ha skjer dersom prisnivået P øker? Vis grafisk og verbalt.

_Svar:_

_Grafisk: Se forelesningsnotatene._

_Verbalt:_

_Økt priser ____ Redusert realpengemengde ___ _økt nominell rente__ _ _redusert konsum og investeringer ___ _redusert etterspørsel__ _ _redusert produksjon ___ _redusert disponibel inntekt__ _ _redusert konsum etc._

_For AS-Kurven vil økte priser være assosiert med redusert produksjon._

- Diskuter fordeler og ulemper ved pengepolitikk vs. finanspolitikk som stabiliseringspolitiske verktøy.

_Svar:_

_Pengepolitikk funger raskere enn finanspolitikk._

_Finanspolitikk kan være svært effektivt i en likvidietsfelle (vi kommer  til dette sener)_

_Finanspolitikk øker offentlig sektor på bekostning av privat sektor. Politiske preferanser avgjør om dette er bra eller dårlig._

**Oppgaver gitt til 5. forelesning**

- Vi tar først utgangspunkt i samme modell som ble satt opp under oppgave gitt til 3. forelesning. Videre tenker vi oss at økonomien er åpen for handel og kapitalbevegelser med utlandet. Dette betyr nå at

Z=C+I+G+NX

Y=Z

                                        NX≡X−R∗ℑ

E❑=(1+i)(1+i❑)E❑e

I tillegg postulerer vi at følgende sammenhenger for import og eksport:

X(R,Y)=A´+−a1R+−a2Y

ℑ(R,Y)=B´+−s1R+−s2Y

                                R=EPP

Anta at parameterne a1,a2,s1ogs2
 er positive Bestem og forklar hvilke fortegn (+/-) som bør gjelde for eksport og import likningene ovenfor.

_Svar:_

X(R,Y)=A´+a1R+a2Y

ℑ(R,Y)=B´−s1R+s2Y

-
Finn et uttrykk for ∆NX∆Y
 ,
∆NX∆R
 og om mulig avgjør fortegnene.
 , ∆NX∆R
 og om mulig avgjør fortegnene.
 og om mulig avgjør fortegnene.

_Svar:_

ΔNX=−Rs2∆Y&gt;0

⇔

ΔNXΔY=−Rs2&gt;0

ΔNX=(a1−(B´−s1R+s2Y)+Rs1)∆R&gt;0

⇔

ΔNX∆R=(a1−(B´−s1R+s2Y)+Rs1)&gt;0

Matematiskikkemuligåavgjørefortegnet,menviantar&gt;0

eroppfyltivåremodeller(Marshall−Lernerbetingelsen)
.

- Finn et eksplisitt utrykk for IS likningen under faste kurs (enklest).

_Svar:_

_Merk først: Fast kurs betyr at_ E=Ee_så realvalutakursen R holdes her uendret._

_Innsetting for NX gir_

Y=c0+c1(Y−T)−c2i+I´−b1i+G

+[(A´+a1R+Y)−R(B´−s1R+s2Y)]

 Løst mhp. Y:

B´−s1R(A´+a1R+Y)−RY(1−c1+Rs2)=c0−c1T−c2i+I´−b1i+G+

c0−c1T−c2i+I´−b1i+G+(A´+a1R+Y)−R(B´−s1R)Y=1(1−c1+Rs2)

IS-kurven som også gir likevekt i valutakursmarkedet finner vi da ved å differensiere ΔY
mph på
Δi

ΔY=−1(1−c1+Rs2)[c2+b2]∆i&gt;0

⇔

ΔY∆i=−1(1−c1+Rs2)[c2+b2]&gt;0

- Finn et eksplisitt utrykk for IS likningen under flytende kurs (mer vanskelig).

_Svar:_

Merk først: Flytende kurs betyr at

E=1+i1+iEe

R=1+i1+iEePP

IS-kurven som også gir likevekt i valutakursmarkedet finner vi da ved å differensiere ΔY
mph på
Δi

ΔY=1(1−c1+Rs2)[−c2−b2−∆NX∆R]∆i&gt;0

⇔

∆Y∆i=1(1−c1+Rs2)[−c2−b2−∆NX∆R]&gt;0

Vi får med et ekstra ledd, sammenliknet med løsningen under fast kurs. Dette leddet er gitt ved

Hvor

∆NX∆R=[(a1−(B´−s1R+s2Y)+Rs1)]Ee(1+i)&gt;0

- I løpet av forelesningen ble det hevdet at importlekkasje gjør multiplikatoren mindre. I tillegg til dette, vil helningen på IS-kurven (likevekt i vare- og valutakursmarkedet) være brattere i et under fast kurs sammenliknet flytene kurs. Er dette overens med løsningen du fant i de to oppgavene ovenfor?

_Svar:_

_Ja, det stemmer. Importlekkasjen gitt ved_ Rs2_dukker opp i nevneren i multiplikatoren. Videre_

_Helningen på IS-kurvene er slakere under flytende kurs som en følge av at vi inkluder leddet_ ∆NX∆R_. Dette leddet reflekterer forbedringen i handelsbalansen som en konsekvens av det lavere rentenivået medfører en depresiering av den nominelle valutakursen._

- Hvilke virkemidler har myndighetene for å stabilisere konjunkturene under henholdsvis et fast og flytende kurs regime?

_Svar:_

_Flytende kurs: renta (i) og finanspolitikk (G og T)_

_Fast kurs: finanspolitikk (G og T) og E dersom en står utenfor en valutaunion._

- Hva menes med intern og ekstern balanse?

_Svar:_

_Intern balanse vil si produksjon og ledighet er lik sitt naturlige ledighetsnivå._

_Ekstern balanse vil si at utenlandsgjelden er på et bærekraftig nivå._

_ _

**Oppgaver gitt til 6. forelesning**

-
Basert på de forutsetningene som har blitt gjort i oppgaver gitt til 5. forelesning, finn  ∆NX∆P
 og avgjør fortegnet.
 og avgjør fortegnet.

_Svar:_

ΔNX=(−a1EPP2ΔP+(B´−s1R+s2Y)EPP2ΔP−s1EPP2ΔP)&gt;0

⇔

∆NX∆P=(−a1EPP2+(B´−s1R+s2Y)EPP2−s1EPP2)&lt;0

-
Finn deretter  ∆Y∆P
 og tegn AD-kurven inn i to diagrammer, et for fast og et for flytende kurs (slapp av, vil ikke bli bedt om å utlede dette formelt på eksamen).
 og tegn AD-kurven inn i to diagrammer, et for fast og et for flytende kurs (slapp av, vil ikke bli bedt om å utlede dette formelt på eksamen).

_Svar:_

_Modellen for varemarkedet løst mhp. Y_

c0−c1T−c2i+I´−b1i+G+(A´+a1R+Y)−R(B´−s1R)Y=1(1−c1+Rs2)

_Differensiering av_ ΔY _mhp.  _ΔP _gir_

c0−c1T−c2i+I´−b1i+G+(A´+a1R+Y)−R(B´−s1R)∆P+1(1−c1+Rs2)(−a1EPP2+(B´−s1R+s2Y)EPP2−s1EPP2)ΔP∆Y=s2(1−c1+Rs2)2EPP2

⇔

c0−c1T−c2i+I´−b1i+G+(A´+a1R+Y)−R(B´−s1R)+1(1−c1+Rs2)(−a1EPP2+(B´−s1R+s2Y)EPP2−s1EPP2)&lt;0∆Y∆P=s2(1−c1+Rs2)2EPP2

knyttettilmultiplimatorenMmatematiskikkemuligåavgjøre,menviantaratførsteeffekten

forimportlekkasjeervesentligmindre(iabsoluttverdi)enndenandreeffekten.

- Tegn til slutt AS-kurven inn i de to diagrammene.

_Svar:_

_AS-kurven er som under en lukket økonoi: Økt produksjon fører til økte priser som følge økt lønninger. Sistnevnte er knyttet til bedre forhandlingsposisjon hos arbeiderne som følge av lavere ledighet)._

-
Anta at vi får en sterk økning i C´.

_Svar:_

_AD-kurven skifter til høyre, som i en periode gir både høyere produksjon og høyere priser. Økningen i produksjonen stopper opp i det prisforventningene er korrekte_ P=Pe__Y=Yn_og_ u=un.

- Hva skjer med handelsbalansen?

_Svar:_

_Høyere produksjon svekker handelsbalansen:_

_                _ ΔNX∆Y=−Rs2&gt;0

_Høyere priser svekker handelsbalansen:_

∆NX∆P=(−a1EPP2+(B´−s1R+s2Y)EPP2−s1EPP2)&lt;0

_(begge disse utrykkene er blitt utledet i tidligere oppgaver)_

- Hva skjer med utenriksregnskapet?

_Svar:_

CU+CA=0(utenriksregnskapet)

ΔCU=ΔNX&lt;0
 Nettoeksporten reduseres.

_Det motsvares av en tilsvarende økning i nettokapitalimporten (tilsvarer økt låneopptak i utlandet)_

ΔCU=ΔNX=−ΔCA

_Merk at økt nettokapitalimport fører til økt utenlandsgjeld med tilhørende renteforpliktelser i neste periode. Har landet problemet med å betjene denne gjelden, har vi oppnådd en situasjon med ekstern ubalanse._



- Hvorfor vil det under en slik endring være enklere å føre en stabiliseringspolitikk i et flytende vs. et fast kurs regime?

_Svar:_

_Under fast kurs vil renta måtte brukes til å forsvare valutakursen. Rentenivået vil derfor være bestemt av rentenivået utenlands. Dersom renta som blir satt i utlandet ikke samsvarer med den renta som trengs på hjemmebane, vil rente opphøre å fungere som et politisk stabiliseringsverktøy._

**Oppgaver gitt til 7. forelesning**

-
Solow-modellen består av tre komponenter ((1) produktfunksjonen på intensiv form, (2) sparing per innbygger og (3) uttrykk for kapitalakkumulasjon). Utled disse sammenhengene formelt under antagelsen om at  ∆AA=a=0
 og
∆NN
=n=0 og vis deretter den grafiske løsningen av modellen.
 og ∆NN
=n=0 og vis deretter den grafiske løsningen av modellen.
=n=0 og vis deretter den grafiske løsningen av modellen.

_Svar:_

_Se forelesningsnotatene._

- Hva menes med at modellen går mot en steady state?

_Svar:_

_Uavhengig av startnivået på kapitalen (_k0_) vil økonomien over tid konvergere mot et konstant nivå på y:  _yss=Yss/Nss _._

-
Anta nå  ∆NN
=n&gt;0. Finn et utrykk for
∆k
.
=n&gt;0. Finn et utrykk for ∆k
.
.

_Svar:_

_Vi kan starte først med å differensiere_ k=K/N _som gir_

Δk=ΔKN−KN2ΔN=ΔKN−kn

Vi trenger nå et utrykk for ΔK/N
. Vi har at

YN=f(k)

,

Kt+1=(1−δ)Kt+It

og

S=I⇔IN=sYN=sf(k)

Det gir

ΔK=−δK+I

ΔK/N=−δK/N+I/N

ΔK/N=−δk+sy

Ved å sette det siste uttrykket inn i det første utrykket vi utledet får vi:

Δk=−δk+sy−kn=sy−(δ+n)k

- Hva er produksjonsveksten i denne økonomien i steady state?

_Svar:_

Ylna(ss)−lna(Nss)lna(yss)=

Ylna(ss)=lna(Nss)

_                                        Tidsderivasjon gir_

Yss´Yss=Nss´Nss=n

_Produksjonsveksten vokser med en rate n som er lik befolkningsveksten._

- Solow-modellen er uten noen forklaring på hva som skaper teknologisk framgang (parameteren a er bestemt utenfor modellen). Hva mener du kan gjøres for å øke veksten i denne parameteren?

_Svar:_

_Utdanning, bedre institusjoner, helsevesen, bedre lover og regler etc._

**Oppgaver gitt til 8. forelesning**

- Finn ved bruk av FRED M0 (M1) og M2 for USA i årene før og etter finanskrisen og vis disse tallene grafisk

_Svar:_

_Benytt Fred-Excel plugg inn på ditt regneark._

- Fra talleksempelet under system 2, finn for banksektoren som helhet:

Reserveandelen

Kapitalandelen

M0

M1

_Svar:_

_Reserveandelen er gitt ved reserver/innskudd=150/300=0,5 (50 prosent)_

_Kapitalandelen er gitt ved egenkapital/sum balanse =         25/350=0,0833 (8,3 prosent)_

_M0 =200_

_M1=150+200=350_

- Kvantitative lettelser:

Ta utgangspunkt i talleksemplet under system 3, anta videre at sentralbanken ved å bruke av seddelpressen ønsker å kjøpe statsobligasjoner til 500 og et bilfirma til 600. Hvordan vil balansene se ut etter en slik endring?

_Svar:_

_X=500 og T=600._

- Dersom forretningsbank 1 oppnår et bratt fall i sine reserver, hvilke to muligheter gir system 3 for at banken skal kunne øke sin likviditet

_Svar:_

1. (1)_Interbanklån fra forretningsbank 1 og (2) refinansieringslån fra sentralbanken._

- Refinansieringslån:

Ta utgangspunkt i talleksemplet under system 3, anta videre at interbankmarkedet er &quot;frosset&quot; grunnet manglene tillit mellom forretningsbankene.  Hvordan vil balansen se ut dersom sentralbanken låner forretningsbanken et beløp på 75

_Svar:_

_Y1=Y2=75_

- Hva tror du vil skje med utlånene til banksektoren dersom kapitalkravene for banksektoren øker?

_Svar:_

_Øke kapitalkrav kan oppnås ved en reduksjon i innskudd. Når innskuddene reduseres må også eiendelssiden reduseres tilsvarende. Holdes reservene konstante, vil dette bety at utlånene går ned (mao. innvendig penger blir redusert)._

**Oppgaver gitt til 9. forelesning**

- Benytt regneksemplet som ble gitt navnet the BLOOS rule, og finn den forventede avkastningen på egenkapital og statlige overføringer under et egenkapitalkrav på 20 og 99 prosent.

_Svar:_

_0,20 gir forventet avkastning på egenkapital på 0,092 og statlige overføringer på 0,84._

_0,99 gir forventet avkastning på egenkapital på 0,05 og statlige overføringer på 0,01._

- Tegn to grafer. Begge grafene har graden av egenkapital på den horisontale aksen, mens den første har forventet avkastning på egenkapital på den vertikale aksen mens den andre har forventet statlige overføringer.  Plot inn verdiene du får for egenkapitalkrav på 5, 10, 20 og 99 prosent for de to bankene.

_Svar:_

_Vist under forelesningen._

- I Fronter finn fram regnearket for the Bloos rule.  For forretningsmodell 1, legg inn for tilstand 1 at avkastningen skal være 0,056 mot tidligere 0,0606.

_Svar:_

_Endringene må gjøres i celle C57 i filen BloosRuleExcel.xlsk_

- Under situasjonen med en 100 prosent bailout garanti, for hvilken egenkapitalnivå  vil bank 2 være indifferent mellom å investere i de to forretningsmodellene?

_Svar:_

_Ca. 0,55. Svaret finner man prøve seg fram med litt forskjellig verdier i regnearket BloosRuleExcel.xlsk_

**Oppgaver gitt til 10. forelesning**

- Ta utgangspunkt i de tre likningene for offentlig sektor

       Finansdepartementet

Btf=(1+it−1)Bt−1f+(Gt−Tt)−SNGt

Sentralbanken

SNGt+∆Btm=∆Mt+it−1Bt−1m

Statsgjeld

Bt=Btf−Btm

Forsøk å gi en tolkning av hver enkelt likning

_Svar:_

_Finansdepartementet_

_Gjeld i dag er lik forrige periodes gjeld pluss rentekostnader, pluss underskuddet på den primære budsjettbalansen fratrukket utbytte (seigniorage) fra sentralbanken_

_Sentralbanken:_

_Kjøper statsgjeld ved å øke basispengemengden og gir utbetalinger for obligasjonene som utbytte (seigniorage) til finansdepartmentet  _

_Statsgjeld:_

_Offentlig gjeld eies av både private aktører og sentralbanken._

- Vis ved innsetting at det er mulig å skrive de tre likningene (konsolidert budsjettbetingelse for offentlig sektor) som

Bt=(1+it−1)Bt+(Gt−Tt)−ΔMt

_Svar:_

_Kombinere de to første likningene gir_

Btf=(1+it−1)Bt−1f+(Gt−Tt)−(∆Mt+it−1Bt−1m−∆Btm)

ΔBtf−ΔBtm=(it−1)Bt−1f−Bt−1m+(Gt−Tt)−∆Mt

Δ(Btf−Btm)=(it−1)(Bt−1f−Bt−1m)+(Gt−Tt)−∆Mt

_Innsetter deretter for likningen for statsgjeld_

ΔBt=it−1∙Bt−1+(Gt−Tt)−∆Mt

Bt−Bt−1=it−1∙Bt−1+(Gt−Tt)−∆Mt

Bt=(1+it−1)Bt−1+(Gt−Tt)−∆Mt

Bt=(1+it−1)Bt+(Gt−Tt)−ΔMt

-
Vi antar null inflasjon, slik at  it=rt
 og
ΔMt=0
 . Omgjør likningen ovenfor på en slik form at
 og ΔMt=0
 . Omgjør likningen ovenfor på en slik form at
 . Omgjør likningen ovenfor på en slik form at

BtYt=(Gt−Tt)Yt+Bt−1Yt−1(1+r−g)

_Svar:_

BtYt=(1+r)Bt−1Yt+(Gt−Tt)Yt

BtYt=(1+r)BtYt−1Yt∙Yt−1+(Gt−Tt)Yt

_Vi lar veksten i BNP vær gitt ved en konstant rate_ g_:_Yt−Yt−1Yt−1=g⇔YtYt−1=g+1

_Innsetting av dett gir_

BtYt=(1+r)Bt1(1+g)Yt1+(Gt−Tt)Yt

_Vi kan videre bruke at_

1+r1+g≈1+r−g

BtYt=(Gt−Tt)Yt+(1+r−g)Bt−1Yt−1

-
Vis i en figur den dynamiske utviklingen over tid for BtYt
 i en situasjon hvor (1+r-g)&lt;1 og  (i)
(Gt−Tt)
&gt;0  og (ii)
(Gt−Tt)
&lt;0. Går den offentlige gjeldsandelen mot en steady state i de to tilfellene?
 i en situasjon hvor (1+r-g)&lt;1 og  (i) (Gt−Tt)
&gt;0  og (ii)
(Gt−Tt)
&lt;0. Går den offentlige gjeldsandelen mot en steady state i de to tilfellene?
&gt;0  og (ii) (Gt−Tt)
&lt;0. Går den offentlige gjeldsandelen mot en steady state i de to tilfellene?
&lt;0. Går den offentlige gjeldsandelen mot en steady state i de to tilfellene?

_Svar: Ja, begge modellen går mot en steady state. Se Blanchard boka for grafisk løsning._

**Oppgaver gitt til 11. forelesning**

- Hva menes innenfor økonomi med en likviditetsfelle?

_Svar: En situasjon hvor pengepoltikken ikke lengre kan ha en ekspansiv effekt på økonomien. Dette fordi den nominelle rente er (nær) lik null._

- Ifølge forskning utført av Krugman er det spesielt to forhold som kan lede et land inn i en likviditetsfelle. Nevn disse.

_Svar:_

_Demografiske endringer som fører til pessimistiske framtidsutsikter og dermed redusert konsum (  _ΔC´&lt;0_)_

_Gjeldsnedbygging i privat sektor (Minsky beveglse) (_Dlav−DhøyΔDb=_)&lt;0)_

- Hva menes med en Minsky bevegelse (deleveraging shock)?

_Svar:_

_Krav om rask nedbetaling av gjeld som en konsekvens av økt usikkerhet tilknyttet husholdningene evne til å betjene gjeld._

- Ta utgangspunkt i IS-(LM) modellen benyttet i forelesningen for dette temaet. Hvilken betingelse må være oppfylt for at en økonomi skal havne i en likviditetsfelle som følge av en Minsky bevegelse (deleveraging)

_Svar:_

_Vi har havnet i en likviditetsfelle__dersom rentereduksjon ikke er tilstrekkelig til å motvirke fallet i konsumetterspørselen_

(θ∙ΔDb−b´∙Δi0)&lt;0

- Hvorfor kan det oppstå en nær sammenheng mellom en privat og statlig gjeldskrise?

_Svar:_

_En privat gjeldskrise som gjør at vi havner i en likviditetsfelle vi bety lavere produksjon og  mindre skatteinntekter. Begge er faktorer som vil svekke den primære budsjettbalansen og dermed øke statsgjelden som andel av BNP. Dette kan initiere en statlig gjeldskrise._

**Regneregler for differensiering til bruk i dette kurset**

∆∆x(α)=0

∆∆x(αX)=α∆x

∆∆x(f(x)g(x))=f&#39;(x)g(x)Δx+f(x)g&#39;(x)Δx

∆∆x(f(x)g(x))=f&#39;(x)g(x)Δx−f(x)g(x)2g&#39;(x)∆x
