---
output:
  pdf_document: default
  word_document: default
  html_document: default
---
<!--
---
title: "Oppgaver ØKB1115 Makroøkonomi"
output: html_notebook
---
-->
# Del I: Konjunktursvingninger
## Seminar 1: Datatransformering av nasjonalregnskapstal

Gjør følgende oppgaver for Norge, Tyskland og enten Hellas, Spania, Portugal eller Italia.

### Installering av FRED applikasjon til Excel
- Installer applikasjonen FRED (fra Federal Reserve Bank of St. Louis)  i ditt Excel regneark [klikk her for næmere instruksjon](https://research.stlouisfed.org/fred-addin/install_windows.html)

- Hjelp og tips til bruk av programmet finnes her:
[Youtube](http://www.youtube.com/watch?v=OAH-wGtP_k8)

### Tidsserier
- Hent tidsserien til bruttonasjonalproduktet i real størrelser
- Transformer denne serien ved å ta logaritmen 
- Hent en tidsserie for arbeidsledighet 
- Hent en tidsserie for prisindeksen 
- Vis tidsseriene grafisk
- Gir serien noen tegn på dype økonomiske kriser?  Hvis ja, se om du kan finne (ved søk på internett) noen kortfattede økonomiske forklaringer bak disse krisene

### Okuns lov og Phillips-kurven
- Finn et mål på inflasjon
- Finn et mål på ledighet
- Lag et scatterplot for vekst og endring i inflasjon (Okuns lov)
- Lag et scatterplot for ledighet og endring inflasjon (Phillips-kurven).
- For de to scatterplottene, se om du klarer å estimere en linje for graden av lineær korrelasjon
- Er resultaten du finner i tråd med de empirisk regularitetene som ble gjennomgått i forelesningen?

# Del II: Økonomisk vekst

# Del III: Økonomiske kriser
